import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Topheader from "./components/Topheader";
import Header from "./components/Header";
import Links from "./components/Links";
import Footer from "./components/Footer";
import Hero from "./components/Hero";
import Products from "./components/Products";
import TopCategories from "./components/Categories";
import Explore from "./components/Explore";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
  
        <div className="min-h-screen flex flex-col">
        
         


          <main className="flex-1 max-w-7xl mx-auto container">
          <Topheader />
            <Header />

          <Links />
            <Hero />
            <Products />
            <TopCategories />
            <Explore />
            

            
            <Footer />
          </main>

        
        </div>
      </body>
    </html>
  );
}
